//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxChampionship.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battles
    {
        public int BattleId { get; set; }
        public int Winner { get; set; }
        public int Looser { get; set; }
        public int ChampionshipId { get; set; }
        public int Rounds { get; set; }
        public System.DateTime DateTime { get; set; }
        public int WinnerPoints { get; set; }
        public int LooserPoints { get; set; }
    
        public virtual Boxers Boxers { get; set; }
        public virtual Boxers Boxers1 { get; set; }
        public virtual Championship Championship { get; set; }
    }
}
