//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxChampionship.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoxChampionshipDBEntities : DbContext
    {
        public BoxChampionshipDBEntities()
            : base("name=BoxChampionshipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Battles> Battles { get; set; }
        public virtual DbSet<Boxers> Boxers { get; set; }
        public virtual DbSet<Championship> Championship { get; set; }
    }
}
